{
 "title": "Jmeter Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Response time per request",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "90th percentile for each request",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th percentile for each request",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Response Time Per Request every minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT mean(\"responseTime\") FROM \"autogen\".\"requestsRaw\" WHERE $timeFilter GROUP BY time($__interval), \"requestName\" fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "requestName" ], "type": "tag" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "No Of Request Vs Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "requestsRaw",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "virtualUsers",
     "select": [
      [
       { "params": [ "maxActiveThreads" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}